#define BLYNK_PRINT Serial // Comment this out to disable prints and save space 
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>
#include <SimpleTimer.h>
#include <TimeLib.h>

TimeLib tt;
char auth[] = "34c8a75373404b31aed2be71cab0727"; //insert here your token generated by Blynk
SimpleTimer mytimer; // allocate a name (mytimer) to the timer

int relay1 = 5;//D1
int relay2 = 4;//D2

int relayVButton1 = 0;
int relayVButton2 = 0;
int scenario1 = 0;

boolean relayState1 = 1;
boolean relayState2 = 1;

void setup() {
  Serial.begin(115200); // See the connection status in Serial Monitor
  Blynk.begin(auth, "iPhone", "11223344");
  mytimer.setInterval(2000L, somefunction);
  
  pinMode(relay1, OUTPUT);
  pinMode(relay2, OUTPUT);
  
   Serial.print ( tt.tmTime() );
  
   if ( relayVButton1 > 0) {
    relayState1 = !relayState1;
  }
  digitalWrite(relay1, relayState1);

  if ( relayVButton2 > 0) {
    relayState2 = !relayState2;
  }
  digitalWrite(relay2, relayState2);
  
  BLYNK_WRITE(V1)
  {
    // Get the state of the VButton
    relayVButton1 = param.asInt();
  }

  BLYNK_WRITE(V2)
  {
    // Get the state of the VButton
    relayVButton2 = param.asInt();
  }
  
  void loop() {
    Blynk.run();
    mytimer.run(); // call the simple timer routine
  }
